apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  # This defines which pods are going to be represented by this service
  # The Service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: activemq
  ports:
    - name: http
      port: 8161
      # targetPort is set to port by default
      nodePort: 30010
  type: NodePort
