apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # This defines which pods are going to be represented by this service
  # The Service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp
    release: 0
  ports:
    - name: http
      port: 80
      # targetPort is set to port by default
      nodePort: 30080
  type: NodePort
